(define-module (gnucash report balance-linechart))
(use-modules (gnucash main)) ;; FIXME: delete after we finish modularizing.
(use-modules (srfi srfi-1)) ;;needed for printf I think
(use-modules (ice-9 slib)) ;;needed for printf I think
(use-modules (gnucash gnc-module))

(require 'printf)

(debug-enable 'debug)
(debug-enable 'backtrace)

(gnc:module-load "gnucash/report/report-system" 0)
(gnc:module-load "gnucash/gnome-utils" 0) ;for gnc-build-url

(define optname-marker (N_ "Marker"))
(define optname-markercolor (N_ "Marker Color"))
(define optname-plot-width (N_ "Plot Width"))
(define optname-plot-height (N_ "Plot Height"))

(define optname-from-date (N_ "From"))
(define optname-to-date (N_ "To"))
(define optname-stepsize (N_ "Step Size"))

(define (options-generator)    
  (let* ((options (gnc:new-options)) 
         ;; This is just a helper function for making options.
         ;; See gnucash/src/scm/options.scm for details.
         (add-option 
          (lambda (new-option)
            (gnc:register-option options new-option))))

    (gnc:options-add-date-interval!
     options gnc:pagename-general
     optname-from-date optname-to-date "a")

    (gnc:options-add-interval-choice!
     options gnc:pagename-general optname-stepsize "b" 'MonthDelta)

    (add-option
     (gnc:make-color-option
      gnc:pagename-display (N_ "Background Color")
      "f" (N_ "This is a color option")
      (list #xf6 #xff #xdb 0)
      255
      #f))
    (add-option
     (gnc:make-color-option
      gnc:pagename-display (N_ "Text Color")
      "f" (N_ "This is a color option")
      (list #x00 #x00 #x00 0)
      255
      #f))

    (gnc:options-add-plot-size! 
     options gnc:pagename-display 
     optname-plot-width optname-plot-height "c" 500 400)

    (gnc:options-add-marker-choice!
     options gnc:pagename-display 
     optname-marker "a" 'filledsquare)

    (add-option
     (gnc:make-color-option
      gnc:pagename-display optname-markercolor
      "b"
      (N_ "Color of the marker")
      (list #xb2 #x22 #x22 0)
       255 #f))

    (gnc:options-set-default-section options gnc:pagename-general)
    options))

(define (balance-linechart-renderer report-obj)
  ;; These are some helper functions for looking up option values.
  (define (get-option section name)
    (gnc:lookup-option (gnc:report-options report-obj) section name))
  
  (define (op-value section name)
    (gnc:option-value (get-option section name)))

  ;; The first thing we do is make local variables for all the specific
  ;; options in the set of options given to the function. This set will
  ;; be generated by the options generator above.
  (let* ((bg-color-op  (get-option   gnc:pagename-display "Background Color"))
        (txt-color-op (get-option   gnc:pagename-display "Text Color"))
        (report-title (get-option gnc:pagename-general 
                                   gnc:optname-reportname))
         (height (get-option gnc:pagename-display optname-plot-height))
         (width (get-option gnc:pagename-display optname-plot-width))
         (marker (get-option gnc:pagename-display optname-marker))
         (mcolor 
          (gnc:color-option->hex-string
           (gnc:lookup-option (gnc:report-options report-obj)
                              gnc:pagename-display optname-markercolor)))

;;TESTING TESTING 1 2 2 2 2
	(testvalue (get-option gnc:pagename-general optname-to-date)) ;;is ok
;;	(testvalue2 (gnc:date-option-absolute-time (testvalue)));;fails
;;	(testvalue (gnc:date-option-absolute-time(get-option gnc:pagename-general optname-to-date))) ;;fails

        (document (gnc:make-html-document))
         (chart (gnc:make-html-scatter)))

	;; Here's where we fill the report document with content.
	(gnc:html-document-set-style!
	document "body" 
	'attribute (list "bgcolor" (gnc:color-option->html bg-color-op))
	'font-color (gnc:color-option->html txt-color-op))
	
	;; the title of the report
	(gnc:html-document-set-title! document (_ "Balance line chart"))
      document))

;; Here we define the actual report
(gnc:define-report
 'version 1
 'name (N_ "Balance line chart")
 'report-guid "6f78b99926754df1ba01019831079fe8"
 'menu-tip (N_ "Plot account balance over time.")
 'menu-path (list gnc:menuname-asset-liability)
 'options-generator options-generator
 'renderer balance-linechart-renderer)
